[package]
name = "rebalance-app"
version = "1.2.0"
authors = ["Alberto Leal <mailforalberto@gmail.com>"]

[dependencies]
csv = "1.1.1"
tabwriter = "1.2.1"
clap = "2.33.0"
num = "0.2.0"
chrono = "0.4.6"
